default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: three_joys_development

test:
  <<: *default
  database: three_joys_test
